[package]
name = "neural_nobble"
version = "0.1.0"
edition = "2021"

[lib]
name = "neural_nobble"
path = "src/lib.rs"

[dependencies]
image = "0.25.5"
mnist = "0.6.0"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.9.0"

[features]
neural_nobble_log = []
